### PR TITLE
Upped dependency versions to work with node v4.1.2

### PR DESCRIPTION
**Pull request by RobertBrewitz**
Tests pass and example works.

Due to the following:

> ws@0.4.32 install /usr/local/lib/node_modules/coffee-collider/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o

> speaker@0.0.10 install /usr/local/lib/node_modules/coffee-collider/node_modules/speaker
> node-gyp rebuild

  CC(target) Release/obj.target/output/deps/mpg123/src/output/coreaudio.o
  LIBTOOL-STATIC Release/liboutput.a
  CXX(target) Release/obj.target/binding/src/binding.o
In file included from ../src/binding.cc:6:
../src/node_pointer.h:23:9: error: unexpected namespace name 'Buffer': expected expression
  node::Buffer *buf = node::Buffer::New((char *)ptr, length, wrap_pointer_cb, user_data);
        ^
../src/node_pointer.h:23:17: error: use of undeclared identifier 'buf'
  node::Buffer *buf = node::Buffer::New((char *)ptr, length, wrap_pointer_cb, user_data);
                ^
../src/node_pointer.h:23:23: error: no matching function for call to 'New'
  node::Buffer *buf = node::Buffer::New((char *)ptr, length, wrap_pointer_cb, user_data);
                      ^~~~~~~~~~~~~~~~~
/Users/robertbrewitzborg/.node-gyp/4.1.2/include/node/node_buffer.h:31:40: note: candidate function not viable: requires at most 3 arguments, but 4 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/robertbrewitzborg/.node-gyp/4.1.2/include/node/node_buffer.h:43:40: note: candidate function not viable: requires 3 arguments, but 4 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/robertbrewitzborg/.node-gyp/4.1.2/include/node/node_buffer.h:36:40: note: candidate function not viable: requires 5 arguments, but 4 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/robertbrewitzborg/.node-gyp/4.1.2/include/node/node_buffer.h:28:40: note: candidate function not viable: requires 2 arguments, but 4 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length);
                                       ^
In file included from ../src/binding.cc:6:
../src/node_pointer.h:24:10: error: use of undeclared identifier 'buf'
  return buf->handle_;
         ^
../src/binding.cc:17:3: error: unknown type name 'uv_work_t'
  uv_work_t req;
  ^
../src/binding.cc:25:27: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
Handle<Value> Open (const Arguments& args) {
                          ^~~~~~~~~
                          v8::internal::Arguments
/Users/robertbrewitzborg/.node-gyp/4.1.2/include/node/v8.h:139:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/binding.cc:26:15: error: calling a protected constructor of class 'v8::HandleScope'
  HandleScope scope;
              ^
/Users/robertbrewitzborg/.node-gyp/4.1.2/include/node/v8.h:885:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../src/binding.cc:28:77: error: type 'const v8::internal::Arguments' does not provide a subscript operator
  audio_output_t *ao = reinterpret_cast<audio_output_t *>(UnwrapPointer(args[0]));
                                                                        ~~~~^~
../src/binding.cc:31:30: error: type 'const v8::internal::Arguments' does not provide a subscript operator
  Local<Object> format = args[1]->ToObject();
                         ~~~~^~
../src/binding.cc:33:38: error: no member named 'NewSymbol' in 'v8::String'
  ao->channels = format->Get(String::NewSymbol("channels"))->Int32Value(); /* channels */
                             ~~~~~~~~^
../src/binding.cc:34:34: error: no member named 'NewSymbol' in 'v8::String'
  ao->rate = format->Get(String::NewSymbol("sampleRate"))->Int32Value(); /* sample rate */
                         ~~~~~~~~^
../src/binding.cc:36:38: error: no member named 'NewSymbol' in 'v8::String'
  int bitDepth = format->Get(String::NewSymbol("bitDepth"))->Int32Value();
                             ~~~~~~~~^
../src/binding.cc:37:39: error: no member named 'NewSymbol' in 'v8::String'
  bool isSigned = format->Get(String::NewSymbol("signed"))->BooleanValue();
                              ~~~~~~~~^
../src/binding.cc:38:38: error: no member named 'NewSymbol' in 'v8::String'
  bool isFloat = format->Get(String::NewSymbol("float"))->BooleanValue();
                             ~~~~~~~~^
../src/binding.cc:72:16: error: no member named 'Close' in 'v8::HandleScope'
  return scope.Close(Integer::New(r));
         ~~~~~ ^
../src/binding.cc:72:36: error: too few arguments to function call, expected 2, have 1
  return scope.Close(Integer::New(r));
                     ~~~~~~~~~~~~  ^
/Users/robertbrewitzborg/.node-gyp/4.1.2/include/node/v8.h:2499:3: note: 'New' declared here
  static Local<Integer> New(Isolate* isolate, int32_t value);
  ^
../src/binding.cc:75:19: error: unknown type name 'uv_work_t'
void write_async (uv_work_t *);
                  ^
../src/binding.cc:76:19: error: unknown type name 'uv_work_t'
void write_after (uv_work_t *);
                  ^
../src/binding.cc:78:28: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
Handle<Value> Write (const Arguments& args) {
                           ^~~~~~~~~
                           v8::internal::Arguments
/Users/robertbrewitzborg/.node-gyp/4.1.2/include/node/v8.h:139:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/binding/src/binding.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/coffee-collider/node_modules/speaker
gyp ERR! node -v v4.1.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "coffee-collider"
npm ERR! node v4.1.2
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE

npm ERR! speaker@0.0.10 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the speaker@0.0.10 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the speaker package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls speaker
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/robertbrewitzborg/npm-debug.log

### CODE REVIEW

**Comment by RobertBrewitz** [comment]
I'll check the ci config :P

**Comment by RobertBrewitz** [comment]
I'm not familiar with Travis CI and their box setup, works locally but can't get it to work on Travis CI.

**Comment by RobertBrewitz** [comment]
Ok, there we go, now Travis CI likes the config.

**Comment by mohayonao** [comment]
thanks :+1:
